# Generated by Django 3.0.4 on 2020-03-20 07:31

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='jenis_kelamin',
            field=models.SmallIntegerField(choices=[(1, 'Laki-laki'), (2, 'Perempuan')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='nama',
            field=models.CharField(max_length=255, validators=[dashboard.validators.validate_nama]),
        ),
    ]
